/**
 * Learnir Javascript
 * Welcome to the Learnir Javascript sdk, get your content right in the browser anywhere and everywhere.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Box model module.
 * @module model/Box
 * @version 1.0.0
 */
class Box {
    /**
     * Constructs a new <code>Box</code>.
     * Base of content boxes, is dynamic though
     * @alias module:model/Box
     */
    constructor() { 
        
        Box.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Box</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Box} obj Optional instance to populate.
     * @return {module:model/Box} The populated <code>Box</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Box();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
Box.prototype['id'] = undefined;

/**
 * @member {String} title
 */
Box.prototype['title'] = undefined;

/**
 * @member {String} description
 */
Box.prototype['description'] = undefined;






export default Box;

