/**
 * Learnir Javascript
 * Welcome to the Learnir Javascript sdk, get your content right in the browser anywhere and everywhere.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Consumer model module.
 * @module model/Consumer
 * @version 1.0.0
 */
class Consumer {
    /**
     * Constructs a new <code>Consumer</code>.
     * Creation of a User to allow access to locked resources
     * @alias module:model/Consumer
     */
    constructor() { 
        
        Consumer.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Consumer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Consumer} obj Optional instance to populate.
     * @return {module:model/Consumer} The populated <code>Consumer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Consumer();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
Consumer.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Consumer.prototype['name'] = undefined;

/**
 * @member {String} email
 */
Consumer.prototype['email'] = undefined;






export default Consumer;

