/**
 * Learnir Javascript
 * Welcome to the Learnir Javascript sdk, get your content right in the browser anywhere and everywhere.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Box from './model/Box';
import Consumer from './model/Consumer';
import LearnirApi from './api/LearnirApi';


/**
* Welcome_to_the_Learnir_Javascript_sdk_get_your_content_right_in_the_browser_anywhere_and_everywhere_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var LearnirJavascript = require('index'); // See note below*.
* var xxxSvc = new LearnirJavascript.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new LearnirJavascript.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new LearnirJavascript.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new LearnirJavascript.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Box model constructor.
     * @property {module:model/Box}
     */
    Box,

    /**
     * The Consumer model constructor.
     * @property {module:model/Consumer}
     */
    Consumer,

    /**
    * The LearnirApi service constructor.
    * @property {module:api/LearnirApi}
    */
    LearnirApi
};
